services:
  mongo:
    image: mirror.gcr.io/library/mongo:8
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin_user
      MONGO_INITDB_ROOT_PASSWORD: web3
    ports:
      - "27017:27017"
    networks:
      - mongo-network

  calculadora:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: calculadora-fast-api:latest
    ports:
      - "8089:8000"
    networks:
      - mongo-network
    volumes:
      - ./backend:/app
    environment:
      MONGO_URI: mongodb://admin_user:web3@mongo:27017/
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app         # Copia el código del host a /app dentro del contenedor
      - /app/node_modules       # Evita conflictos con node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - calculadora
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge